# Generated by Django 4.2.6 on 2023-10-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_modificación',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
