# Generated by Django 4.2.6 on 2023-10-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_entidadadmin_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_modificado', to='miapp.entidad'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_publicado', to='miapp.entidad'),
        ),
        migrations.DeleteModel(
            name='EntidadAdmin',
        ),
    ]
