# Generated by Django 4.2.6 on 2023-10-24 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0005_alter_comunicado_modificado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_publicado', to=settings.AUTH_USER_MODEL),
        ),
    ]
